//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MiniMarket.Model.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class FakturyZakupuPozycje
    {
        public int Fvz_PozycjeId { get; set; }
        public string Fvz_PozycjeKod { get; set; }
        public string Fvz_PozycjeNazwa { get; set; }
        public Nullable<decimal> Fvz_PozycjeIlosc { get; set; }
        public string Fvz_PozycjeJm { get; set; }
        public Nullable<decimal> Fvz_Rabat { get; set; }
        public Nullable<decimal> Fvz_PozycjeCenaNetto { get; set; }
        public Nullable<byte> Fvz_PozycjeVatZakup { get; set; }
        public Nullable<byte> Fvz_PozycjeVatSprzedaz { get; set; }
        public Nullable<decimal> Fvz_PozycjeCenaBrutto { get; set; }
        public Nullable<int> Fvz_PozycjeWprowId { get; set; }
        public Nullable<System.DateTime> Fvz_PozycjeDataWprow { get; set; }
        public Nullable<int> Fvz_PozycjeZmienId { get; set; }
        public Nullable<System.DateTime> Fvz_PozycjeDataZmien { get; set; }
        public Nullable<bool> Fvz_PozycjeCzyAktywne { get; set; }
        public Nullable<int> Fvz_PozycjeIdTowaru { get; set; }
        public Nullable<int> Fvz_PozycjeKategoriaId { get; set; }
        public Nullable<int> Fvz_IdFvZakup { get; set; }
    
        public virtual FakturyZakupu FakturyZakupu { get; set; }
        public virtual Towary Towary { get; set; }
    }
}
