//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MiniMarket.Model.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class FakturySprzedazy
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public FakturySprzedazy()
        {
            this.FakturySprzedazyPozycje = new HashSet<FakturySprzedazyPozycje>();
            this.TowaryIlosci = new HashSet<TowaryIlosci>();
        }
    
        public int Fvs_IdSprzedaz { get; set; }
        public string Fvs_NrDok { get; set; }
        public Nullable<int> Fvs_IdKontrahent { get; set; }
        public Nullable<int> Fvs_IdKategoria { get; set; }
        public Nullable<int> Fvs_IdMagazyn { get; set; }
        public Nullable<System.DateTime> Fvs_DataWyst { get; set; }
        public Nullable<System.DateTime> FvsDataSprzedazy { get; set; }
        public Nullable<System.DateTime> FvsDataOd { get; set; }
        public Nullable<decimal> FvsRabat { get; set; }
        public string Fvs_PlatnoscTyp { get; set; }
        public Nullable<System.DateTime> Fvs_Termin { get; set; }
        public Nullable<int> Fvs_IdPozycji { get; set; }
        public Nullable<int> Fvs_WprowId { get; set; }
        public Nullable<System.DateTime> Fvs_DataWprow { get; set; }
        public Nullable<int> Fvs_ZmienId { get; set; }
        public Nullable<System.DateTime> FvsDataZmian { get; set; }
        public Nullable<bool> CzyAktywne { get; set; }
        public Nullable<int> Fvs_IdKontrahentOdb { get; set; }
        public Nullable<int> Fvs_IdDokNettoBrutto { get; set; }
        public Nullable<int> Fvs_IdRodzajDokumentu { get; set; }
        public Nullable<int> Fvs_IdRodzajPlatnosci { get; set; }
    
        public virtual Kontrahenci Kontrahenci { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FakturySprzedazyPozycje> FakturySprzedazyPozycje { get; set; }
        public virtual DokumentNettoBrutto DokumentNettoBrutto { get; set; }
        public virtual Kategorie Kategorie { get; set; }
        public virtual Magazyny Magazyny { get; set; }
        public virtual RodzajeDokumentow RodzajeDokumentow { get; set; }
        public virtual RodzajePlatnosci RodzajePlatnosci { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TowaryIlosci> TowaryIlosci { get; set; }
    }
}
