//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MiniMarket.Model.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class FakturyZakupu
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public FakturyZakupu()
        {
            this.FakturyZakupuPozycje = new HashSet<FakturyZakupuPozycje>();
            this.TowaryIlosci = new HashSet<TowaryIlosci>();
        }
    
        public int Fvz_IdZakup { get; set; }
        public string Fvz_NrDok { get; set; }
        public Nullable<int> Fvz_IdKontrahent { get; set; }
        public Nullable<int> Fvz_IdKategoria { get; set; }
        public Nullable<int> Fvz_IdMagazyn { get; set; }
        public Nullable<System.DateTime> Fvz_DataWyst { get; set; }
        public Nullable<System.DateTime> FvzDataSprzedazy { get; set; }
        public Nullable<System.DateTime> FvzDataOd { get; set; }
        public Nullable<decimal> FvzRabat { get; set; }
        public string Fvz_PlatnoscTyp { get; set; }
        public Nullable<System.DateTime> Fvz_Termin { get; set; }
        public Nullable<int> Fvz_IdPozycji { get; set; }
        public Nullable<int> Fvz_WprowId { get; set; }
        public Nullable<System.DateTime> Fvz_DataWprow { get; set; }
        public Nullable<int> Fvz_ZmienId { get; set; }
        public Nullable<System.DateTime> FvzDataZmian { get; set; }
        public Nullable<bool> CzyAktywne { get; set; }
        public Nullable<int> Fvz_IdTowaru { get; set; }
        public Nullable<int> Fvz_IdKontrahentOdb { get; set; }
        public Nullable<int> Fvz_IdDokNettoBrutto { get; set; }
        public Nullable<int> Fvz_IdRodzajDokumentu { get; set; }
        public Nullable<int> Fvz_IdRodzajPlatnosci { get; set; }
    
        public virtual Kontrahenci Kontrahenci { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FakturyZakupuPozycje> FakturyZakupuPozycje { get; set; }
        public virtual DokumentNettoBrutto DokumentNettoBrutto { get; set; }
        public virtual Magazyny Magazyny { get; set; }
        public virtual RodzajeDokumentow RodzajeDokumentow { get; set; }
        public virtual RodzajePlatnosci RodzajePlatnosci { get; set; }
        public virtual Kategorie Kategorie { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TowaryIlosci> TowaryIlosci { get; set; }
    }
}
