//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MiniMarket.Model.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class FakturySprzedazyPozycje
    {
        public int Fvs_PozycjeId { get; set; }
        public Nullable<int> Fvs_PozycjeIdTowaru { get; set; }
        public Nullable<int> Fvs_PozycjeIdKategori { get; set; }
        public string Fvs_PozycjeKod { get; set; }
        public string Fvs_PozycjeNazwa { get; set; }
        public Nullable<decimal> Fvs_PozycjeIlosc { get; set; }
        public string Fvs_PozycjeJm { get; set; }
        public Nullable<decimal> Fvs_Rabat { get; set; }
        public Nullable<decimal> Fvs_PozycjeCenaNetto { get; set; }
        public Nullable<byte> Fvs_PozycjeVatZakup { get; set; }
        public Nullable<byte> Fvs_PozycjeVatSprzedaz { get; set; }
        public Nullable<decimal> Fvs_PozycjeCenaBrutto { get; set; }
        public Nullable<int> Fvs_PozycjeWprowId { get; set; }
        public Nullable<System.DateTime> Fvs_PozycjeDataWprow { get; set; }
        public Nullable<int> Fvs_PozycjeZmienId { get; set; }
        public Nullable<System.DateTime> Fvs_PozycjeDataZmien { get; set; }
        public Nullable<bool> Fvs_PozycjeCzyAktywne { get; set; }
        public Nullable<int> Fvs_IdFvSprzedaz { get; set; }
    
        public virtual FakturySprzedazy FakturySprzedazy { get; set; }
        public virtual Towary Towary { get; set; }
    }
}
