//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MiniMarket.Model.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class GrupyTowarowe
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public GrupyTowarowe()
        {
            this.Towary = new HashSet<Towary>();
        }
    
        public int G_GRId { get; set; }
        public string G_GRNazwa { get; set; }
        public Nullable<bool> G_GRAktywna { get; set; }
        public string G_GRWprowadzil { get; set; }
        public Nullable<System.DateTime> G_GRDataWprowadzenia { get; set; }
        public string G_GRZmienil { get; set; }
        public Nullable<System.DateTime> G_GRDataZmiany { get; set; }
        public Nullable<bool> G_CzyAktywne { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Towary> Towary { get; set; }
    }
}
