//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MiniMarket.Model.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Kontrahenci
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Kontrahenci()
        {
            this.FakturySprzedazy = new HashSet<FakturySprzedazy>();
            this.FakturyZakupu = new HashSet<FakturyZakupu>();
            this.Paragony = new HashSet<Paragony>();
            this.PZ = new HashSet<PZ>();
            this.Rezerwacje = new HashSet<Rezerwacje>();
            this.WZ = new HashSet<WZ>();
            this.Zamowienia = new HashSet<Zamowienia>();
        }
    
        public int Knt_KntId { get; set; }
        public Nullable<short> Knt_PodmiotTyp { get; set; }
        public string Knt_Kod { get; set; }
        public string Knt_GLN { get; set; }
        public string Knt_IdSisc { get; set; }
        public string Knt_EAN { get; set; }
        public string Knt_Grupa { get; set; }
        public string Knt_Nazwa1 { get; set; }
        public string Knt_Nazwa2 { get; set; }
        public string Knt_Nazwa3 { get; set; }
        public string Knt_Kraj { get; set; }
        public string Knt_Wojewodztwo { get; set; }
        public string Knt_Powiat { get; set; }
        public string Knt_Gmina { get; set; }
        public string Knt_Ulica { get; set; }
        public string Knt_NrDomu { get; set; }
        public string Knt_NrLokalu { get; set; }
        public string Knt_Miasto { get; set; }
        public string Knt_KodPocztowy { get; set; }
        public string Knt_Poczta { get; set; }
        public string Knt_Adres2 { get; set; }
        public string Knt_NipKraj { get; set; }
        public string Knt_NipE { get; set; }
        public string Knt_Nip { get; set; }
        public string Knt_Regon { get; set; }
        public string Knt_Pesel { get; set; }
        public string Knt_Telefon1 { get; set; }
        public string Knt_Telefon2 { get; set; }
        public string Knt_TelefonSms { get; set; }
        public string Knt_Fax { get; set; }
        public string Knt_Email { get; set; }
        public string Knt_URL { get; set; }
        public string Knt_KrajISO { get; set; }
        public string Knt_Zezwolenie { get; set; }
        public string Knt_KodTransakcji { get; set; }
        public string Knt_RachunekNr { get; set; }
        public Nullable<short> Knt_IBAN { get; set; }
        public string Knt_Wpowadzil { get; set; }
        public Nullable<System.DateTime> Knt_DataWprowadzenia { get; set; }
        public string Knt_Zmienil { get; set; }
        public Nullable<System.DateTime> Knt_dataZmiany { get; set; }
        public Nullable<bool> Knt_CzyAktywny { get; set; }
        public Nullable<int> Knt_IdKategori { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FakturySprzedazy> FakturySprzedazy { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FakturyZakupu> FakturyZakupu { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Paragony> Paragony { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PZ> PZ { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Rezerwacje> Rezerwacje { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<WZ> WZ { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Zamowienia> Zamowienia { get; set; }
        public virtual Kategorie Kategorie { get; set; }
    }
}
