//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MiniMarket.Model.Entities
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class MiniMarketEntities : DbContext
    {
        public MiniMarketEntities()
            : base("name=MiniMarketEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Kontrahenci> Kontrahenci { get; set; }
        public virtual DbSet<Kategorie> Kategorie { get; set; }
        public virtual DbSet<Firmy> Firmy { get; set; }
        public virtual DbSet<GrupyTowarowe> GrupyTowarowe { get; set; }
        public virtual DbSet<Uzytkownicy> Uzytkownicy { get; set; }
        public virtual DbSet<FakturySprzedazy> FakturySprzedazy { get; set; }
        public virtual DbSet<FakturySprzedazyPozycje> FakturySprzedazyPozycje { get; set; }
        public virtual DbSet<FakturyZakupu> FakturyZakupu { get; set; }
        public virtual DbSet<FakturyZakupuPozycje> FakturyZakupuPozycje { get; set; }
        public virtual DbSet<Paragony> Paragony { get; set; }
        public virtual DbSet<ParagonyPozycje> ParagonyPozycje { get; set; }
        public virtual DbSet<PZ> PZ { get; set; }
        public virtual DbSet<PzPozycje> PzPozycje { get; set; }
        public virtual DbSet<Rezerwacje> Rezerwacje { get; set; }
        public virtual DbSet<RezerwacjePozycje> RezerwacjePozycje { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<Towary> Towary { get; set; }
        public virtual DbSet<TowaryIlosci> TowaryIlosci { get; set; }
        public virtual DbSet<WZ> WZ { get; set; }
        public virtual DbSet<WzPozycje> WzPozycje { get; set; }
        public virtual DbSet<Zamowienia> Zamowienia { get; set; }
        public virtual DbSet<ZamowieniaPozycje> ZamowieniaPozycje { get; set; }
        public virtual DbSet<CenaDomyslna> CenaDomyslna { get; set; }
        public virtual DbSet<JednostkaPodstawowa> JednostkaPodstawowa { get; set; }
        public virtual DbSet<JednostkaPomocnicza> JednostkaPomocnicza { get; set; }
        public virtual DbSet<TypTowaru> TypTowaru { get; set; }
        public virtual DbSet<VatSprzedaz> VatSprzedaz { get; set; }
        public virtual DbSet<VatZakup> VatZakup { get; set; }
        public virtual DbSet<DokumentNettoBrutto> DokumentNettoBrutto { get; set; }
        public virtual DbSet<Magazyny> Magazyny { get; set; }
        public virtual DbSet<RodzajeDokumentow> RodzajeDokumentow { get; set; }
        public virtual DbSet<RodzajePlatnosci> RodzajePlatnosci { get; set; }
    }
}
