//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MiniMarket.Model.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class ParagonyPozycje
    {
        public int Par_PozycjeId { get; set; }
        public Nullable<int> Par_PozycjeIdTowaru { get; set; }
        public Nullable<int> Par_PozycjeIdKategori { get; set; }
        public string Par_PozycjeKod { get; set; }
        public string Par_PozycjeNazwa { get; set; }
        public Nullable<decimal> Par_PozycjeIlosc { get; set; }
        public string Par_PozycjeJm { get; set; }
        public Nullable<decimal> Par_Rabat { get; set; }
        public Nullable<decimal> Par_PozycjeCenaNetto { get; set; }
        public Nullable<byte> Par_PozycjeVatZakup { get; set; }
        public Nullable<byte> Par_PozycjeVatSprzedaz { get; set; }
        public Nullable<decimal> Par_PozycjeCenaBrutto { get; set; }
        public Nullable<int> Par_PozycjeWprowId { get; set; }
        public Nullable<System.DateTime> Par_PozycjeDataWprow { get; set; }
        public Nullable<int> Par_PozycjeZmienId { get; set; }
        public Nullable<System.DateTime> Par_PozycjeDataZmien { get; set; }
        public Nullable<bool> Par_PozycjeCzyAktywne { get; set; }
        public Nullable<int> Par_IdParagonu { get; set; }
    
        public virtual Paragony Paragony { get; set; }
        public virtual Towary Towary { get; set; }
    }
}
