//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MiniMarket.Model.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class PZ
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PZ()
        {
            this.PzPozycje = new HashSet<PzPozycje>();
        }
    
        public int Pz_IdPZ { get; set; }
        public string Pz_NrDok { get; set; }
        public Nullable<int> Pz_IdKontrahent { get; set; }
        public Nullable<int> Pz_IdKontrahentOdbiorca { get; set; }
        public Nullable<int> Pz_IdKategoria { get; set; }
        public Nullable<int> Pz_IdMagazyn { get; set; }
        public Nullable<System.DateTime> Pz_DataWyst { get; set; }
        public Nullable<System.DateTime> Pz_DataSprzedazy { get; set; }
        public Nullable<System.DateTime> Pz_DataOd { get; set; }
        public Nullable<decimal> Pz_Rabat { get; set; }
        public string Pz_PlatnoscTyp { get; set; }
        public Nullable<System.DateTime> Pz_Termin { get; set; }
        public Nullable<int> Pz_IdPozycji { get; set; }
        public Nullable<int> Pz_WprowId { get; set; }
        public Nullable<System.DateTime> Pz_DataWprow { get; set; }
        public Nullable<int> Pz_ZmienId { get; set; }
        public Nullable<System.DateTime> Pz_DataZmian { get; set; }
        public Nullable<bool> Pz_CzyAktywne { get; set; }
        public Nullable<int> Pz_IdDokNettoBrutto { get; set; }
        public Nullable<int> Pz_IdRodzajDokumentu { get; set; }
        public Nullable<int> Pz_RodzajPlatnosci { get; set; }
    
        public virtual Kontrahenci Kontrahenci { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PzPozycje> PzPozycje { get; set; }
        public virtual DokumentNettoBrutto DokumentNettoBrutto { get; set; }
        public virtual Kategorie Kategorie { get; set; }
        public virtual Magazyny Magazyny { get; set; }
        public virtual RodzajeDokumentow RodzajeDokumentow { get; set; }
        public virtual RodzajePlatnosci RodzajePlatnosci { get; set; }
    }
}
