//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MiniMarket.Model.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class PzPozycje
    {
        public int Pz_PozycjeId { get; set; }
        public Nullable<int> Pz_PozycjeIdTowaru { get; set; }
        public Nullable<int> Pz_PozycjeIdKategori { get; set; }
        public string Pz_PozycjeKod { get; set; }
        public string Pz_PozycjeNazwa { get; set; }
        public Nullable<decimal> Pz_PozycjeIlosc { get; set; }
        public string Pz_PozycjeJm { get; set; }
        public Nullable<decimal> Pz_Rabat { get; set; }
        public Nullable<decimal> Pz_PozycjeCenaNetto { get; set; }
        public Nullable<byte> Pz_PozycjeVatZakup { get; set; }
        public Nullable<byte> Pz_PozycjeVatSprzedaz { get; set; }
        public Nullable<decimal> Pz_PozycjeCenaBrutto { get; set; }
        public Nullable<int> Pz_PozycjeWprowId { get; set; }
        public Nullable<System.DateTime> Pz_PozycjeDataWprow { get; set; }
        public Nullable<int> Pz_PozycjeZmienId { get; set; }
        public Nullable<System.DateTime> Pz_PozycjeDataZmien { get; set; }
        public Nullable<bool> Pz_PozycjeCzyAktywne { get; set; }
        public Nullable<int> Pz_IdPZ { get; set; }
    
        public virtual PZ PZ { get; set; }
        public virtual Towary Towary { get; set; }
    }
}
