//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MiniMarket.Model.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Rezerwacje
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Rezerwacje()
        {
            this.RezerwacjePozycje = new HashSet<RezerwacjePozycje>();
        }
    
        public int Rez_IdRezerwacji { get; set; }
        public string Rez_NrDok { get; set; }
        public Nullable<int> Rez_IdKontrahent { get; set; }
        public Nullable<int> Rez_IdKontrahentOdbiorca { get; set; }
        public Nullable<int> Rez_IdKategoria { get; set; }
        public Nullable<int> Rez_IdMagazyn { get; set; }
        public Nullable<System.DateTime> Rez_DataWyst { get; set; }
        public Nullable<System.DateTime> Rez_DataSprzedazy { get; set; }
        public Nullable<System.DateTime> Rez_DataOd { get; set; }
        public Nullable<decimal> Rez_Rabat { get; set; }
        public string Rez_PlatnoscTyp { get; set; }
        public Nullable<System.DateTime> Rez_Termin { get; set; }
        public Nullable<int> Rez_IdPozycji { get; set; }
        public Nullable<int> Rez_WprowId { get; set; }
        public Nullable<System.DateTime> Rez_DataWprow { get; set; }
        public Nullable<int> Rez_ZmienId { get; set; }
        public Nullable<System.DateTime> Rez_DataZmian { get; set; }
        public Nullable<bool> Rez_CzyAktywne { get; set; }
        public Nullable<int> Rez_IdDokNettoBrutto { get; set; }
        public Nullable<int> Rez_IdRodzajDokumentu { get; set; }
        public Nullable<int> Rez_IdRodzjaPlatnosci { get; set; }
    
        public virtual Kontrahenci Kontrahenci { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RezerwacjePozycje> RezerwacjePozycje { get; set; }
        public virtual DokumentNettoBrutto DokumentNettoBrutto { get; set; }
        public virtual Kategorie Kategorie { get; set; }
        public virtual Magazyny Magazyny { get; set; }
        public virtual RodzajeDokumentow RodzajeDokumentow { get; set; }
        public virtual RodzajePlatnosci RodzajePlatnosci { get; set; }
    }
}
