//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MiniMarket.Model.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class RezerwacjePozycje
    {
        public int Rez_PozycjeId { get; set; }
        public Nullable<int> Rez_PozycjeIdTowaru { get; set; }
        public Nullable<int> Rez_PozycjeIdKategori { get; set; }
        public string Rez_PozycjeKod { get; set; }
        public string Rez_PozycjeNazwa { get; set; }
        public Nullable<decimal> Rez_PozycjeIlosc { get; set; }
        public string Rez_PozycjeJm { get; set; }
        public Nullable<decimal> Rez_Rabat { get; set; }
        public Nullable<decimal> Rez_PozycjeCenaNetto { get; set; }
        public Nullable<byte> Rez_PozycjeVatZakup { get; set; }
        public Nullable<byte> Rez_PozycjeVatSprzedaz { get; set; }
        public Nullable<decimal> Rez_PozycjeCenaBrutto { get; set; }
        public Nullable<int> Rez_PozycjeWprowId { get; set; }
        public Nullable<System.DateTime> Rez_PozycjeDataWprow { get; set; }
        public Nullable<int> Rez_PozycjeZmienId { get; set; }
        public Nullable<System.DateTime> Rez_PozycjeDataZmien { get; set; }
        public Nullable<bool> Rez_PozycjeCzyAktywne { get; set; }
        public Nullable<int> Rez_IdRezerwacje { get; set; }
    
        public virtual Rezerwacje Rezerwacje { get; set; }
        public virtual Towary Towary { get; set; }
    }
}
