//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MiniMarket.Model.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Towary
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Towary()
        {
            this.FakturySprzedazyPozycje = new HashSet<FakturySprzedazyPozycje>();
            this.FakturyZakupuPozycje = new HashSet<FakturyZakupuPozycje>();
            this.ParagonyPozycje = new HashSet<ParagonyPozycje>();
            this.PzPozycje = new HashSet<PzPozycje>();
            this.RezerwacjePozycje = new HashSet<RezerwacjePozycje>();
            this.TowaryIlosci = new HashSet<TowaryIlosci>();
            this.WzPozycje = new HashSet<WzPozycje>();
            this.ZamowieniaPozycje = new HashSet<ZamowieniaPozycje>();
        }
    
        public int Twr_IdTowaru { get; set; }
        public string Twr_Kod { get; set; }
        public string Twr_NumerKat { get; set; }
        public Nullable<int> Twr_IdGrupa { get; set; }
        public string Twr_Typ { get; set; }
        public Nullable<bool> Twr_Opak_Kaucja { get; set; }
        public string Twr_EAN { get; set; }
        public string Twr_PKWiU { get; set; }
        public Nullable<byte> Twr_VatSpr { get; set; }
        public Nullable<byte> Twr_VatZak { get; set; }
        public Nullable<decimal> Twr_CenaDomysl { get; set; }
        public string Twr_Nazwa { get; set; }
        public Nullable<int> Twr_IdKatSprzedazy { get; set; }
        public Nullable<int> Twr_IdKatZakupu { get; set; }
        public string Twr_JednPodst { get; set; }
        public string Twr_JednPomoc { get; set; }
        public Nullable<decimal> Twr_CenaZakNetto { get; set; }
        public Nullable<decimal> Twr_CenaZakBrutto { get; set; }
        public Nullable<decimal> Twr_CenaSprNetto { get; set; }
        public Nullable<decimal> Twr_CenaSprBrutto { get; set; }
        public Nullable<decimal> Twr_Marza { get; set; }
        public string Twr_Waluta { get; set; }
        public Nullable<int> Twr_WprUzytkId { get; set; }
        public Nullable<System.DateTime> Twr_WprUzytData { get; set; }
        public Nullable<int> Twr_ZmienUzytId { get; set; }
        public Nullable<System.DateTime> Twr_ZmiUzytData { get; set; }
        public Nullable<bool> Twr_CzyAktywne { get; set; }
        public Nullable<int> Twr_IdKategoria { get; set; }
        public string Twr_IdTowaryIlosci { get; set; }
        public Nullable<int> Twr_IdVatSprzedaz { get; set; }
        public Nullable<int> Twr_IdVatZakup { get; set; }
        public Nullable<int> Twr_IdJednostkaPodstawowa { get; set; }
        public Nullable<int> Twr_IdJednostkaPomocnicza { get; set; }
        public Nullable<int> Twr_IdTypTowaru { get; set; }
        public Nullable<int> Twr_CenaDomyslna { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FakturySprzedazyPozycje> FakturySprzedazyPozycje { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FakturyZakupuPozycje> FakturyZakupuPozycje { get; set; }
        public virtual GrupyTowarowe GrupyTowarowe { get; set; }
        public virtual Kategorie Kategorie { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ParagonyPozycje> ParagonyPozycje { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PzPozycje> PzPozycje { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RezerwacjePozycje> RezerwacjePozycje { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TowaryIlosci> TowaryIlosci { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<WzPozycje> WzPozycje { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ZamowieniaPozycje> ZamowieniaPozycje { get; set; }
        public virtual CenaDomyslna CenaDomyslna { get; set; }
        public virtual JednostkaPodstawowa JednostkaPodstawowa { get; set; }
        public virtual JednostkaPomocnicza JednostkaPomocnicza { get; set; }
        public virtual TypTowaru TypTowaru { get; set; }
        public virtual VatSprzedaz VatSprzedaz { get; set; }
        public virtual VatZakup VatZakup { get; set; }
    }
}
