//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MiniMarket.Model.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class TowaryIlosci
    {
        public int Twr_ilosciId { get; set; }
        public Nullable<int> Twr_IdTowaru { get; set; }
        public Nullable<int> Twr_IdFvZakupu { get; set; }
        public Nullable<int> Twr_IdParagon { get; set; }
        public Nullable<int> Twr_IdFvSprzedaz { get; set; }
        public Nullable<decimal> Twr_Ilosc { get; set; }
        public Nullable<decimal> Twr_Wartosc { get; set; }
        public Nullable<decimal> Twr_Zamowienia { get; set; }
        public Nullable<decimal> Twr_Rezerwacje { get; set; }
        public Nullable<decimal> Twr_SprzedazIlosc { get; set; }
        public Nullable<decimal> Twr_ZakupIlosc { get; set; }
        public Nullable<int> Twr_ZmienUzytId { get; set; }
        public Nullable<System.DateTime> Twr_DataZmian { get; set; }
        public Nullable<int> Twr_WprowUzytId { get; set; }
        public Nullable<System.DateTime> Twr_WprowData { get; set; }
        public Nullable<bool> CzyAktywne { get; set; }
        public Nullable<System.DateTime> Twr_DataSprzedaz { get; set; }
        public Nullable<System.DateTime> Twr_DataZakup { get; set; }
        public string Twr_TypDokumentu { get; set; }
        public string Twr_NumerDokumentu { get; set; }
    
        public virtual Towary Towary { get; set; }
        public virtual FakturySprzedazy FakturySprzedazy { get; set; }
        public virtual FakturyZakupu FakturyZakupu { get; set; }
        public virtual Paragony Paragony { get; set; }
    }
}
