//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MiniMarket.Model.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Uzytkownicy
    {
        public int U_UzytkownikId { get; set; }
        public string U_UZNazwa { get; set; }
        public string U_UZTelefon { get; set; }
        public string U_UZStanowisko { get; set; }
        public Nullable<bool> U_UZCzyAdmin { get; set; }
        public Nullable<bool> U_UZCzyManager { get; set; }
        public Nullable<bool> U_UZCzyPracownik { get; set; }
        public string U_UZWprowadzil { get; set; }
        public Nullable<System.DateTime> U_UZDataWprowadzenia { get; set; }
        public string U_UZZmienil { get; set; }
        public Nullable<System.DateTime> U_UZDataZmiany { get; set; }
        public Nullable<bool> U_UZCzyAktywna { get; set; }
    }
}
