//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MiniMarket.Model.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class WZ
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public WZ()
        {
            this.WzPozycje = new HashSet<WzPozycje>();
        }
    
        public int Wz_IdWZ { get; set; }
        public string Wz_NrDok { get; set; }
        public Nullable<int> Wz_IdKontrahent { get; set; }
        public Nullable<int> Wz_IdKontrahentOdbiorca { get; set; }
        public Nullable<int> Wz_IdKategoria { get; set; }
        public Nullable<int> Wz_IdMagazyn { get; set; }
        public Nullable<System.DateTime> Wz_DataWyst { get; set; }
        public Nullable<System.DateTime> Wz_DataSprzedazy { get; set; }
        public Nullable<System.DateTime> Wz_DataOd { get; set; }
        public Nullable<decimal> Wz_Rabat { get; set; }
        public string Wz_PlatnoscTyp { get; set; }
        public Nullable<System.DateTime> Wz_Termin { get; set; }
        public Nullable<int> Wz_IdPozycji { get; set; }
        public Nullable<int> Wz_WprowId { get; set; }
        public Nullable<System.DateTime> Wz_DataWprow { get; set; }
        public Nullable<int> Wz_ZmienId { get; set; }
        public Nullable<System.DateTime> Wz_DataZmian { get; set; }
        public Nullable<bool> Wz_CzyAktywne { get; set; }
        public Nullable<int> Wz_IdDokNettoBrutto { get; set; }
        public Nullable<int> Wz_IdRodzajDokumentu { get; set; }
        public Nullable<int> Wz_IdRodzajPlatnosci { get; set; }
    
        public virtual Kontrahenci Kontrahenci { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<WzPozycje> WzPozycje { get; set; }
        public virtual DokumentNettoBrutto DokumentNettoBrutto { get; set; }
        public virtual Kategorie Kategorie { get; set; }
        public virtual Magazyny Magazyny { get; set; }
        public virtual RodzajeDokumentow RodzajeDokumentow { get; set; }
        public virtual RodzajePlatnosci RodzajePlatnosci { get; set; }
    }
}
