//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MiniMarket.Model.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class ZamowieniaPozycje
    {
        public int Zam_PozycjeId { get; set; }
        public Nullable<int> Zam_PozycjeIdTowaru { get; set; }
        public Nullable<int> Zam_PozycjeIdKategori { get; set; }
        public string Zam_PozycjeKod { get; set; }
        public string Zam_PozycjeNazwa { get; set; }
        public Nullable<decimal> Zam_PozycjeIlosc { get; set; }
        public string Zam_PozycjeJm { get; set; }
        public Nullable<decimal> Zam_Rabat { get; set; }
        public Nullable<decimal> Zam_PozycjeCenaNetto { get; set; }
        public Nullable<byte> Zam_PozycjeVatZakup { get; set; }
        public Nullable<byte> Zam_PozycjeVatSprzedaz { get; set; }
        public Nullable<decimal> Zam_PozycjeCenaBrutto { get; set; }
        public Nullable<int> Zam_PozycjeWprowId { get; set; }
        public Nullable<System.DateTime> Zam_PozycjeDataWprow { get; set; }
        public Nullable<int> Zam_PozycjeZmienId { get; set; }
        public Nullable<System.DateTime> Zam_PozycjeDataZmien { get; set; }
        public Nullable<bool> Zam_PozycjeCzyAktywne { get; set; }
        public Nullable<int> Zam_IdZamowienia { get; set; }
    
        public virtual Towary Towary { get; set; }
        public virtual Zamowienia Zamowienia { get; set; }
    }
}
